### PR TITLE
Hide tab bars in all windows

### LINKED ISSUE #1: doesn't hide tabs in all panes
With two or more tabs open, the atom-hide-tabs:toggle command only toggles tabs for the topmost-leftmost pane.

### PR DESCRIPTION
**Pull request by javaguirre**
Should close #1

### CODE REVIEW

**Comment by gianmarcotoso** [comment]
Maybe I'm not doing this right, but if I split a panel with tabs hidden, I get the other panel with tabs. Toggling at this point hides the tab bar on the new panel, but restores it on the original one(s). Do you also get this behavior?

**Comment by javaguirre** [comment]
Because how It's done (It works with toggle), I didn't want to change that, but I will improve a bit more the PR.

**Comment by gianmarcotoso** [comment]
Thanks man! I threw this thing together quite hastily so feel free to refactor it however you want. Maybe there should be a subscription to the `pane:attached` event (found [here](https://gist.github.com/ardcore/9262498) but it's quite old, maybe the events are no longer named that way) that calls the toggle just on the attached pane?

**Comment by javaguirre** [comment]
Yes, I was thinking something like that, I already worked on events in the `rest-client` so I think It shouldn't be very difficult to subscribe to an `open-window` kind of event.

**Comment by pzuraq** [comment]
👍 could use this

**Comment by pnevyk** [comment]
What is the status here? I am ready to make my pull request because I didn't notice this one before. My code hides tabs on newly opened pane if they are hidden on the original one. I have also written specs.

**Comment by gianmarcotoso** [comment]
A PR would be very welcome! I'm not using Atom anymore, so I might even be open to giving you full pull access if you want to take over! :)

**Comment by pnevyk** [comment]
Ok, let's do it :) Just tell me what to do

**Comment by pnevyk** [comment]
To make it clear, I mean to give me the full pull access

**Comment by gianmarcotoso** [comment]
You should receive an invite in your email. Thank you! :)

**Comment by pnevyk** [comment]
Thank you, I will make my PR soon and then merge it

**Pull request closed without merging**
